common/models/Order.php
<?php

namespace common\models;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "{{%order}}".
 *
 * @property integer $id
 * @property string $fio
 * @property string $birth_date
 * @property string $phone
 * @property string $gender
 * @property integer $discount_condition_id
 * @property string $created_at
 *
 * @property OrderService[] $orderServices
 * @property Service[] $services
 * @property DiscountCondition $discountCondition
 */
class Order extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%order}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['fio', 'birth_date'], 'required'],
            [['birth_date', 'phone', 'gender'], 'safe'],
            [['fio'], 'string', 'max' => 100],
            [['phone'], 'string', 'max' => 30],
            [['gender'], 'string', 'max' => 1]
        ];
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'TimestampBehavior' => [
                'class' => \yii\behaviors\TimestampBehavior::className(),
                'value' => function () { return date('Y-m-d H:i:s'); },
                'updatedAtAttribute' => null,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'fio' => Yii::t('app', 'Fio'),
            'birth_date' => Yii::t('app', 'Birth Date'),
            'phone' => Yii::t('app', 'Phone'),
            'gender' => Yii::t('app', 'Gender'),
            'created_at' => Yii::t('app', 'Created At'),
            'genderName' => Yii::t('app', 'Gender'),
            'services' => Yii::t('app', 'Services'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrderServices()
    {
        return $this->hasMany(OrderService::className(), ['order_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getServices()
    {
        return $this->hasMany(Service::className(), ['id' => 'service_id'])->via('orderServices')->indexBy('id');
    }

    /**
     * Returns gender name by gender field value
     * @return string
     */
    public function getGenderName()
    {
        return Gender::getGenderName($this->gender);
    }

    /**
     * Returns string representation of entity name
     * @return string
     */
    public function getName()
    {
        return $this->id;
    }

    /**
     * Returns list of entities as id => name
     * @return array
     */
    public static function getList()
    {
        $models = self::find()->all();
        $list = ArrayHelper::map($models, 'id', 'name');
        return $list;
    }


    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDiscountCondition()
    {
        return $this->hasOne(DiscountCondition::className(), ['id' => 'discount_condition_id']);
    }

    /**
     * @inheritdoc
     */
    public function beforeSave($insert)
    {
        if ($this->isNewRecord) {
            $discountCondition = $this->calcDiscountCondition();
            $this->discount_condition_id = ($discountCondition ? $discountCondition->id : null);
        }

        return parent::beforeSave($insert);
    }

    /**
     * Get discount
     *
     * @return mixed|null|string
     */
    public function getDiscount()
    {
        if ($this->discount_condition_id) {
            return $this->discountCondition->discount;
        } elseif ($this->isNewRecord) {
            $condition = $this->calcDiscountCondition();
            if ($condition) {
                return $condition->discount;
            }
            return null;
        }

        return null;
    }

    /**
     * Calculate discount condition
     *
     * @return string|\yii\db\ActiveRecord
     */
    public function calcDiscountCondition()
    {
        $conditions = DiscountCondition::find()
            ->where(['is_active' => 1])
            ->indexBy('id')
            ->all();

        $discounts = array_map(function (DiscountCondition $condition) {
            return ['isPercent' => $condition->isPercent(), 'discount' => $condition->getOrderDiscount($this)];
        }, $conditions);

        $discounts = array_filter($discounts, function ($discountInfo) {
            return ($discountInfo['discount'] !== null);
        });

        if (!$discounts) {
            return '';
        }

        uasort($discounts, function ($a, $b) {
            if ($a['isPercent'] > $b['isPercent']) return 1;
            if ($a['isPercent'] < $b['isPercent']) return -1;
            if ($a['discount'] < $b['discount']) return 1;
            if ($a['discount'] > $b['discount']) return -1;
            return 0;
        });

        $discount_condition_id = key($discounts);

        return $conditions[$discount_condition_id];
    }
}

backend/controllers/OrderController.php
<?php

namespace backend\controllers;

use Yii;
use common\base\CrudController;
use common\models\Order;
use backend\models\OrderSearch;
use yii\helpers\ArrayHelper;
use common\components\UnitOfWork\UnitOfWork;
use yii\db\ActiveRecord;

/**
 * OrderController implements the CRUD actions for Order model.
 */
class OrderController extends CrudController
{
    /**
     * @inheritdoc
     */
    public function init()
	{
		$this->modelClass = Order::className();
		$this->searchModelClass = OrderSearch::className();
	}

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return ArrayHelper::merge(parent::behaviors(), []);
    }

    /**
     * Get Discount
     *
     * @return mixed|null|string
     */
    public function actionGetDiscount()
    {
        $unitOfWork = new UnitOfWork();
        $postData = Yii::$app->request->post();
        $model = new Order();

        if ($postData && $this->loadModel($unitOfWork, $model, $postData)) {

            $discount = $model->getDiscount();
            if (!$discount) {
                $discount = Yii::t('app', 'No discount');
            } else {
                $isPercent = (substr_compare($discount, '%', strlen($discount) - 1) === 0);
                $discount .= ($isPercent ? '' : ' р.');
            }

            return $discount;
        }

        return '';
    }

    /**
     * @inheritdoc
     */
    protected function loadModel(UnitOfWork $unitOfWork, ActiveRecord $model, $postData)
    {
        // fix for data from checkboxes
        if (isset($postData['Order']['services'])) {
            $servicesData = $postData['Order']['services'];
            $servicesData = array_filter($servicesData);
            $postData['Order']['services'] = array_keys($servicesData);
        }

        return parent::loadModel($unitOfWork, $model, $postData);
    }
}

frontend/controllers/OrderController.php
<?php

namespace frontend\controllers;

use Yii;
use backend\controllers\OrderController as BaseOrderController;
use common\base\CrudController;
use common\models\Order;
use yii\helpers\ArrayHelper;
use common\components\UnitOfWork\UnitOfWork;
use yii\db\ActiveRecord;
use yii\web\NotFoundHttpException;

/**
 * OrderController implements the CRUD actions for Order model.
 */
class OrderController extends BaseOrderController
{
    /**
     * @inheritdoc
     */
    public function init()
	{
		$this->modelClass = Order::className();
	}

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [];
    }

    public function actionIndex()
    {
        throw new NotFoundHttpException();
    }

    public function actionUpdate($id)
    {
        throw new NotFoundHttpException();
    }

    public function actionDelete($id)
    {
        throw new NotFoundHttpException();
    }
}

frontend/views/order/_form.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use common\helpers\Render;
use common\models\Gender;
use common\models\Service;
use common\widgets\Script;

/* @var $this yii\web\View */
/* @var $model common\models\Order */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="order-form">

    <?php
        $form = ActiveForm::begin(['id' => 'create-order-form']);

        $render = new Render($form, $model);
    ?>

    <?= $form->field($model, 'fio')->textInput(['maxlength' => true]) ?>

    <div>
        <label><?= Yii::t('app', 'Services') ?></label>
        <br>
        <br>

        <?php foreach (Service::find()->where(['is_active' => 1])->all() as $service) { ?>
            <?= $render->checkboxField('services['.$service->id.']', [
                    'options' => ['value' => isset($model->services[$service->id])]
                ])
                ->label($service->name)
            ?>
        <?php } ?>

        <br>
    </div>

    <?= $render->dateField('birth_date') ?>

    <?= $form->field($model, 'phone', [
            'template' => '
                {label}
                <div class="input-group">
                  <span class="input-group-addon" id="basic-addon1">+7</span>
                  {input}
                </div>
                {hint}
                {error}
            '
        ])->widget(\yii\widgets\MaskedInput::className(), [
            'mask' => '(999) 999-99-99',
        ])
    ?>

    <?= $render->selectField('gender', Gender::getList()); ?>

    <div class="form-group m-t-md">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>

        <?php if ($model->isNewRecord) { ?>
            &nbsp;&nbsp;&nbsp;&nbsp;
            <?= Html::button(
                Yii::t('app', 'Calc discount'),
                ['class' => 'btn btn-primary calc_discount_btn', 'data-url' => Url::to('order/get-discount')]
            ) ?>
            &nbsp;
            <span class="discount_value"></span>
        <?php } ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>


<?php if ($model->isNewRecord) { ?>
    <?php Script::begin(); ?>
        <script>
            $('.calc_discount_btn').click(function(){
                var $btn = $(this);
                $btn.prop('disabled', true);

                $.post(
                    $(this).data('url'),
                    $('input, select, textarea', '#create-order-form').serialize()
                ).success(function (data) {
                    $btn.prop('disabled', false);
                    $('.discount_value').html(data);
                }).error(function (data) {
                    $btn.prop('disabled', false);
                });
            });
        </script>
    <?php Script::end(); ?>
<?php } ?>

frontend/views/order/create.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use common\helpers\UrlHelper;

/* @var $this yii\web\View */
/* @var $model common\models\Order */

$this->title = Yii::t('app', 'Create Order');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="order-create">

    <div class="page-title">
        <h2><?= Html::encode($this->title) ?></h2>
    </div>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/order/view.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\widgets\DetailView;
use common\helpers\UrlHelper;

/* @var $this yii\web\View */
/* @var $model common\models\Order */

$this->title = Yii::t('app', 'Order') . ': ' . $model->id;
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="order-view">

    <div class="page-title">
        <div class="row">
            <div class="col-sm-8">
                <h2><?= Html::encode($this->title) ?></h2>
            </div>
        </div>
    </div>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'fio',
            [
                'attribute' => 'services',
                'format' => 'html',
                'value' => implode('<br>', ArrayHelper::map($model->services, 'id', 'name')),
            ],
            'birth_date:date',
            'phone',
            'genderName',
            'discount',
            'created_at:datetime',
        ],
    ]) ?>

    <?php if ($model->discount_condition_id) { ?>
        <br>
        <h4><?= Yii::t('app', 'Discount Condition') ?></h4>

        <?= DetailView::widget([
            'model' => $model->discountCondition,
            'attributes' => [
                'id',
                [
                    'attribute' => 'services',
                    'format' => 'html',
                    'value' => implode('<br>', ArrayHelper::map($model->services, 'id', 'name')),
                ],
                'birthDateType.name',
                'is_phone_filled:boolean',
                'phone_last_digits',
                'genderName',
                'active_date_from:datetime',
                'active_date_to:datetime',
                'discount',
                'is_active:boolean',
            ],
        ]) ?>
    <?php } ?>

</div>