backend/controllers/DiscountConditionController.php
<?php

namespace backend\controllers;

use Yii;
use common\base\CrudController;
use common\models\DiscountCondition;
use backend\models\DiscountConditionSearch;
use yii\helpers\ArrayHelper;
use common\components\UnitOfWork\UnitOfWork;
use yii\db\ActiveRecord;

/**
 * DiscountConditionController implements the CRUD actions for DiscountCondition model.
 */
class DiscountConditionController extends CrudController
{
    /**
     * @inheritdoc
     */
    public function init()
	{
		$this->modelClass = DiscountCondition::className();
		$this->searchModelClass = DiscountConditionSearch::className();
	}

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return ArrayHelper::merge(parent::behaviors(), []);
    }

    /**
     * @inheritdoc
     */
    protected function loadModel(UnitOfWork $unitOfWork, ActiveRecord $model, $postData)
    {
        // fix for data from checkboxes
        if (isset($postData['DiscountCondition']['services'])) {
            $servicesData = $postData['DiscountCondition']['services'];
            $servicesData = array_filter($servicesData);
            $postData['DiscountCondition']['services'] = array_keys($servicesData);
        }

        return parent::loadModel($unitOfWork, $model, $postData);
    }
}

backend/controllers/ServiceController.php
<?php

namespace backend\controllers;

use Yii;
use common\base\CrudController;
use common\models\Service;
use backend\models\ServiceSearch;
use yii\helpers\ArrayHelper;

/**
 * ServiceController implements the CRUD actions for Service model.
 */
class ServiceController extends CrudController
{
    /**
     * @inheritdoc
     */
    public function init()
	{
		$this->modelClass = Service::className();
		$this->searchModelClass = ServiceSearch::className();
	}

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return ArrayHelper::merge(parent::behaviors(), []);
    }
}

frontend/controllers/OrderController.php
<?php

namespace frontend\controllers;

use Yii;
use backend\controllers\OrderController as BaseOrderController;
use common\base\CrudController;
use common\models\Order;
use yii\helpers\ArrayHelper;
use common\components\UnitOfWork\UnitOfWork;
use yii\db\ActiveRecord;
use yii\web\NotFoundHttpException;

/**
 * OrderController implements the CRUD actions for Order model.
 */
class OrderController extends BaseOrderController
{
    /**
     * @inheritdoc
     */
    public function init()
	{
		$this->modelClass = Order::className();
	}

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [];
    }

    public function actionIndex()
    {
        throw new NotFoundHttpException();
    }

    public function actionUpdate($id)
    {
        throw new NotFoundHttpException();
    }

    public function actionDelete($id)
    {
        throw new NotFoundHttpException();
    }
}

backend/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use common\components\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use backend\assets\AppAsset;
use common\widgets\Alert;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
    </head>
    <body>
        <?php $this->beginBody() ?>

        <div class="wrap">
            <?php
                NavBar::begin([
                    'brandLabel' => 'My Company' . ' - ' . Yii::t('app', 'Admin panel'),
                    'brandUrl' => Yii::$app->homeUrl,
                    'options' => [
                        'class' => 'navbar-inverse navbar-fixed-top',
                    ],
                ]);

                if (Yii::$app->user->isGuest) {
                    // emulate default navigation for guest users
                    $menuItems = [
                        ['label' => Yii::t('app', 'Home'), 'url' => ['/../']],
                    ];
                    $menuItems[] = ['label' => Yii::t('app', 'Login'), 'url' => ['/user/login']];
                    // $menuItems[] = ['label' => Yii::t('app', 'Registration'), 'url' => ['/user/register']];
                } else {
                    $menuItems = [
                        ['label' => Yii::t('app', 'Admin panel'), 'url' => Yii::$app->homeUrl],
                    ];

                    $menuItems[] = ['label' => Yii::t('app', 'Orders'), 'url' => ['/order/index']];
                    $menuItems[] = ['label' => Yii::t('app', 'Discounts'), 'url' => ['/discount-condition/index']];
                    $menuItems[] = ['label' => Yii::t('app', 'Services'), 'url' => ['/service/index']];

                    $menuItems[] = ['label' => Yii::t('app', 'User management'), 'url' => ['/user/admin/index']];

                    $menuItems[] = [
                        'label' => '<span class="glyphicon glyphicon-arrow-right"></span>&nbsp;&nbsp;' . Yii::t('app', 'Site'),
                        'url' => ['/../'],
                        'encode' => false,
                    ];
                    $menuItems[] = [
                        'label' => Yii::t('app', 'Logout') . ' (' . Yii::$app->user->identity->username . ')',
                        'url' => ['/user/logout'],
                        'linkOptions' => ['data-method' => 'post']
                    ];
                }

                echo Nav::widget([
                    'options' => ['class' => 'navbar-nav navbar-right'],
                    'items' => $menuItems,
                ]);

                NavBar::end();
            ?>

            <div class="container">
                <?= Breadcrumbs::widget([
                    'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                ]) ?>

                <?= Alert::widget() ?>
                <?= $content ?>
            </div>
        </div>

        <footer class="footer">
            <div class="container">
                <p class="pull-left">&copy; <?= date('Y') ?></p>
            </div>
        </footer>

        <?php $this->endBody() ?>

        <script>
            $('[data-widget-init]').each(function(){
                var initFunctionName = $(this).attr('data-widget-init');
                window[initFunctionName].apply(this);
            });
        </script>
    </body>
</html>
<?php $this->endPage() ?>